apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-deployment
  labels:
    app: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
        if_using: "0"
    spec:
      containers:
      - name: ocr
        image: registry.cn-hangzhou.aliyuncs.com/k3s_ssh/ocr:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 2Gi
          requests:
            memory: 1Gi
            ephemeral-storage: 2Gi
        ports:
        - name: http
          containerPort: 2500
   


