apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-offload-deployment
  namespace: algorithm
  labels:
    app: polling-offload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polling-offload-deployment
  template:
    metadata:
      labels:
        app: polling-offload-deployment
    spec:
      containers:
      - name: polling-offload-deployment
        image: registry.cn-qingdao.aliyuncs.com/qiaoyufei01/polling-offload-deployment:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 2Gi
          requests:
            memory: 1Gi
            ephemeral-storage: 2Gi
        ports:
        - name: http
          containerPort: 4002
   


