apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment1
  namespace: ai-service
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
        busy: "0"
    spec:
      containers:
      - name: service2
        image: registry.cn-qingdao.aliyuncs.com/qiaoyufei01/ai-ocr:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "3"
            memory: 0.5Gi
            ephemeral-storage: 2Gi
          requests:
            cpu: "3"
            memory: 0.5Gi
            ephemeral-storage: 2Gi
        ports:
        - name: http
          containerPort: 2500
   


