apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddpg-offload-deployment
  namespace: algorithm
  labels:
    app: ddpg-offload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddpg-offload-deployment
  template:
    metadata:
      labels:
        app: ddpg-offload-deployment
    spec:
      containers:
      - name: ddpg-offload-deployment
        image: registry.cn-qingdao.aliyuncs.com/qiaoyufei01/ddpg-offload-deployment:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 2Gi
            ephemeral-storage: 5Gi
          requests:
            memory: 2Gi
            ephemeral-storage: 5Gi
        ports:
        - name: http
          containerPort: 4003
   


