apiVersion: apps/v1
kind: Deployment
metadata:
  name: greedy-offload-deployment
  namespace: algorithm
  labels:
    app: greedy-offload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greedy-offload-deployment
  template:
    metadata:
      labels:
        app: greedy-offload-deployment
    spec:
      containers:
      - name: greedy-offload-deployment
        image: registry.cn-qingdao.aliyuncs.com/qiaoyufei01/greedy-offload-deployment:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 2Gi
          requests:
            memory: 1Gi
            ephemeral-storage: 2Gi
        ports:
        - name: http
          containerPort: 4000
   


